database:
  address: localhost
  database: "rn"
  username: "root"
  password: "root"
  port: 3306

placeholders:
  prefix: "&7[&c&lBossPVE&7] "
  primary: "&7"
  secondary: "&c"
  no_perms: "You do not have permission to do that: %node%"